version: "3"
services:
  web:
    build:
      context: ./src
      dockerfile: ./Dockerfile
      args:
        DOCKER_USER_ID: ${DOCKER_USER_ID}
        DOCKER_GROUP_ID: ${DOCKER_GROUP_ID}
    depends_on:
      - db
    ports:
      - 8000:8000
    env_file: .env
    volumes:
      - ./src:/code
  db:
    image: postgres:10-alpine
    env_file: .env
  mail:
      image: mailhog/mailhog:v1.0.0
      ports:
        - 8025:8025
