version: "3"
services:
  web:
    image: sidneijp/django-shoes-web:latest
    depends_on:
      - db
    ports:
      - 8000:8000
    env_file: .env
  db:
    image: postgres:10-alpine
    env_file: .env
